---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/component: app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/component: app
rules:
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/component: app
roleRef:
  kind: Role
  name: example-app
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: example-app
    namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/component: app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: example
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: example-app
      containers:
      - name: example-app
        image: example-app
        ports:
        - name: http
          protocol: TCP
          containerPort: 4000
        resources: {}
